#!/usr/bin/env tclsh
# INFO: Show SWARM progress, CV sampling and seed production; write xmgrace files
# Requires Tcl 8.5+; no packages.
# Log grammar (first integer is the CV ID):
# SWARM_CYCLE       id cycle RUN run
# SWARM_PROBABILITY id cycles trials ratio
# SEED_OFFER        id cycle replica value
# NEW_SEED          id cycle replica value
# SEED_PROGRESS     id improvements cycles ratio
# Ratios are exported exactly as logged, not interpreted as acceptance rates.
# EXCHANGE lines are always skipped. Input text is NEVER evaluated as Tcl.
# Existing output files with the chosen prefix are replaced on each invocation.

proc usage {} {
    puts {Usage: tclsh get_swarm.tcl [options] [log files or glob patterns ...]
  --input DIR        Read DIR/job*.out (default: output)
  --prefix PATH      Output prefix (default: swarm)
  --x run|cycle      Plot x axis (default: run; counters as logged)
  --summary-only     Print summary without writing files
  --help            Show this help
Examples:
  tclsh get_swarm.tcl
  tclsh get_swarm.tcl --input output --prefix plots/swarm
  tclsh get_swarm.tcl --x cycle job0.out job1.out
  xmgrace swarm_0_progress.agr

Per CV: *_progress.agr (current best seed score), *_spread.agr (offer statistics),
*_replicas.agr (replica offers), *_rates.agr (logged ratios),
*_intervals.agr (RUN spacing between SWARM cycles). Open .agr files directly with xmgrace.
Missing values are omitted from Grace datasets.
Files are read in natural filename order (job2 before job10).
Cycles are keyed by (CV ID, cycle). A later job replaces the WHOLE overlapping
cycle, including offers and seed events. An absent NEW_SEED in the replacement
therefore removes an old NEW_SEED. Unmatched cycles are retained.
For independent calculations, analyze each calculation separately.
Each CV has independent cycle, probability, seed and improvement counters.
RUN is the common simulation axis; --x cycle uses each CV's own cycle counter.
File suffix _0 means CV 0, _1 means CV 1, etc. If only later job logs are read,
the seed remains unknown until the first NEW_SEED for that CV is encountered.
NEW_SEED is used as logged, even when its value is not monotonic.
Performance statistics use the merged history, not the sum of overlapping jobs.
Seed intervals and stagnation are measured in CV cycle-counter increments;
gaps in the available cycle history are reported. Latest logged cumulative
ratios are shown separately. Offer spread is max-minus-min, averaged per cycle.
SWARM spacing is the RUN difference between consecutive cycles of the SAME CV.
It includes RUNs assigned to other CVs. Missing cycle numbers and nonpositive
RUN differences are excluded from spacing statistics. Stagnation instead
measures lack of NEW_SEED events; its RUN duration ends at the latest SWARM
record for that CV, not at the end of the TIGER log.
No physical time, CV units/direction, target, or pool state is inferred.}
}
proc warn {msg} { puts stderr "Warn) $msg" }
proc uint {x} { regexp {^(0|[1-9][0-9]*)$} $x }
proc number {x} {
    if {![regexp {^[+-]?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?$} $x]} { return 0 }
    if {[catch {expr {abs(double($x)) < Inf}} ok]} { return 0 }
    return $ok
}
proc field {row key} {
    if {[dict exists $row $key]} { return [dict get $row $key] }
    return NaN
}
#read fields into the current job; later fields overwrite earlier fields
proc record {id cycle key value} {
    global job_data
    dict set job_data $id $cycle $key $value
}

proc show {value} {
    if {$value eq "NaN"} { return "n/a" }
    return [format %.6g $value]
}

proc ratio {num den} {
    if {$den == 0} { return NaN }
    return [expr {100.0*$num/$den}]
}

proc grace {path title xlabel ylabel sets} {
    set fp [open $path w]
    puts $fp "# Generated by get_swarm.tcl\n@version 50125\n@with g0"
    puts $fp "@title \"$title\"\n@xaxis label \"$xlabel\"\n@yaxis label \"$ylabel\"\n@legend on"
    set i 0
    foreach {label points} $sets {
        puts $fp "@s$i legend \"$label\"\n@target G0.S$i\n@type xy"
        foreach p $points { puts $fp [join $p " "] }
        puts $fp &
        incr i
    }
    puts $fp "@autoscale"
    close $fp
}
proc main {} {
    global argv data job_data
    #setup vars
    set input        output
    set prefix       swarm
    set axis         run
    set summary_only 0
    set patterns     {}

    #read command line
    for {set i 0} {$i < [llength $argv]} {incr i} {
        set a [lindex $argv $i]
        switch -- $a {
            --help - -h { usage; return }
            --summary-only { set summary_only 1 }
            --input - --prefix - --x {
                incr i
                if {$i == [llength $argv]} { error "Missing value for $a" }
                set v [lindex $argv $i]
                switch -- $a { --input {set input $v} --prefix {set prefix $v} --x {set axis $v} }
            }
            -- { set patterns [concat $patterns [lrange $argv [expr {$i+1}] end]]; break }
            default {
                if {[string match -* $a]} { error "Unknown option: $a" }
                lappend patterns $a
            }
        }
    }
    if {$axis ni {run cycle}} { error "--x must be run or cycle" }
    if {![llength $patterns]} { set patterns [list [file join $input job*.out]] }
    set files {}
    foreach p $patterns {
        if {[file isfile $p]} { set matches [list $p] } else { set matches [glob -nocomplain -- $p] }
        if {![llength $matches]} { error "No input files match: $p" }
        foreach f $matches { lappend files [file normalize $f] }
    }
    set files [lsort -unique -dictionary $files]
    #read SWARM histories
    set data      {}
    set replaced  0
    set malformed 0
    set unknown   0
    foreach f $files {
        puts "Info) Browsing [file tail $f]"
        set fp [open $f r]
        fconfigure $fp -encoding utf-8
        set line_no  0
        set job_data {}
        while {[gets $fp line] >= 0} {
            incr line_no
            if {[string first \x00 $line] >= 0} {
                set line [string map [list \x00 ""] $line]
            }
            if {[string first EXCHANGE $line] >= 0} { continue }
            set t [regexp -all -inline {\S+} $line]
            set tag [lindex $t 0]
            if {$tag ni {SWARM_CYCLE SWARM_PROBABILITY SEED_OFFER NEW_SEED SEED_PROGRESS}} {
                if {[regexp {^(SWARM_|SEED_|NEW_SEED|POOL_)} $tag]} { incr unknown }
                continue
            }
            set id [lindex $t 1]
            set a [lindex $t 2]
            set b [lindex $t 3]
            set v [lindex $t 4]
            set valid [expr {[llength $t] == 5 && [uint $id] && [uint $a]}]
            if {$tag eq "SWARM_CYCLE"} {
                set valid [expr {$valid && $b eq "RUN" && [uint $v]}]
            } else {
                set valid [expr {$valid && [uint $b] && [number $v]}]
                if {$tag in {SWARM_PROBABILITY SEED_PROGRESS} && $valid} {
                    set valid [expr {$v >= 0 && $v <= 1}]
                }
            }
            if {!$valid} {
                incr malformed
                if {$malformed <= 5} { warn "Malformed/incomplete record at [file tail $f]:$line_no" }
                continue
            }
            switch -- $tag {
                SWARM_CYCLE {
                    record $id $a run $v
                }
                SEED_OFFER - NEW_SEED {
                    if {$tag eq "SEED_OFFER"} { record $id $a offer,$b $v } else { record $id $a seed [list $b $v] }
                }
                SWARM_PROBABILITY {
                    record $id $a probability $v
                    record $id $a trials $b
                }
                SEED_PROGRESS {
                    record $id $b improvements $a
                    record $id $b progress $v
                }
            }
        }
        close $fp

        #replace complete cycle records, so old seed events cannot survive a restart
        dict for {id cv_data} $job_data {
            dict for {cycle row} $cv_data {
                if {[dict exists $data $id $cycle]} { incr replaced }
                dict set data $id $cycle $row
            }
        }
    }
    if {![dict size $data]} { error "No valid SWARM records found" }
    puts "Info) [llength $files] files; $replaced overlapping cycles replaced; $malformed malformed records; $unknown unsupported SWARM records."
    if {$unknown} { warn "Unsupported SWARM record types were not analyzed." }
    if {!$summary_only} { file mkdir [file dirname $prefix] }
    puts "Info) CV IDs: [join [lsort -integer [dict keys $data]] {, }]"
    #replica IDs are fixed for this calculation; infer them from all offers
    set replica_ids {}
    dict for {id cv_data} $data {
        dict for {cycle row} $cv_data {
            foreach key [dict keys $row offer,*] {
                lappend replica_ids [lindex [split $key ,] 1]
            }
        }
    }
    set replica_ids [lsort -integer -unique $replica_ids]
    set num_replicas [llength $replica_ids]

    #calculate statistics and plotting data for each CV
    foreach id [lsort -integer [dict keys $data]] {
        set offers_total    0
        set seeds_total     0
        set cycles_total    0
        set seed            NaN
        set seed_rank       NaN
        set last_seed       NaN
        set first_seed      NaN
        set replica_sets    {}
        set seed_points     {}
        set min_points      {}
        set mean_points     {}
        set max_points      {}
        set prob_points     {}
        set progress_points {}
        set closed_seeds    0
        set eligible        0
        set spread_sum      0.0
        set spread_count    0
        set intervals       {}
        set previous_seed   NaN
        set previous_cycle  NaN
        set gaps            0
        set idle            0
        set longest_idle    0
        set attempts        {}
        set producers       {}
        set previous_run    NaN
        set last_seed_run   NaN
        set run_intervals   {}
        set interval_points {}
        set spacing_latest  NaN
        set spacing_skipped 0
        set longest_run_idle 0
        set cycles [lsort -integer [dict keys [dict get $data $id]]]
        foreach c $cycles {
            set r [dict get $data $id $c]
            if {$previous_cycle ne "NaN" && $c > $previous_cycle+1} {
                incr gaps [expr {$c-$previous_cycle-1}]
            }
            set run [field $r run]
            set spacing_latest NaN
            if {$previous_cycle ne "NaN"} {
                if {$c == $previous_cycle+1 && $run ne "NaN" && $previous_run ne "NaN" && $run > $previous_run} {
                    set spacing_latest [expr {$run-$previous_run}]
                    lappend run_intervals $spacing_latest
                    set interval_x $c
                    if {$axis eq "run"} { set interval_x $run }
                    lappend interval_points [list $interval_x $spacing_latest]
                } else {
                    incr spacing_skipped
                }
            }
            set previous_cycle $c
            set previous_run $run
            set offers         {}
            set offer_rows     {}
            foreach key [lsort -dictionary [dict keys $r offer,*]] {
                set rank [lindex [split $key ,] 1]
                set val [dict get $r $key]
                lappend offers $val
                lappend offer_rows [list $rank $val]
            }
            set n [llength $offers]
            incr offers_total $n
            set low  NaN
            set high NaN
            set avg  NaN
            if {$n} {
                set sorted [lsort -real $offers]
                set low [lindex $sorted 0]
                set high [lindex $sorted end]
                set sum 0.0
                foreach val $offers { set sum [expr {$sum+$val}] }
                set avg [expr {$sum/$n}]
            }
            if {[dict exists $r seed]} {
                lassign [dict get $r seed] seed_rank seed
                set last_seed $c
                set last_seed_run $run
                incr seeds_total
                if {$first_seed eq "NaN"} { set first_seed $seed }
            }
            #use the final progress record internally to exclude unfinished cycles
            set closed [dict exists $r progress]
            if {$closed} {
                incr eligible
                foreach pair $offer_rows {
                    dict incr attempts [lindex $pair 0]
                }
                if {[dict exists $r seed]} {
                    incr closed_seeds
                    dict incr producers $seed_rank
                    if {$previous_seed ne "NaN"} {
                        lappend intervals [expr {$c-$previous_seed}]
                    }
                    set previous_seed $c
                }
            }
            if {[dict exists $r seed]} {
                set idle 0
            } elseif {$last_seed ne "NaN"} {
                set idle [expr {$c-$last_seed}]
            } else {
                #leading streak is measured only over available cycle numbers
                set idle [expr {$c-[lindex $cycles 0]+1}]
            }
            if {$last_seed_run ne "NaN" && $run ne "NaN" && $run >= $last_seed_run} {
                set run_idle [expr {$run-$last_seed_run}]
                if {$run_idle > $longest_run_idle} { set longest_run_idle $run_idle }
            }
            if {$idle > $longest_idle} { set longest_idle $idle }
            if {$n} {
                set spread_sum [expr {$spread_sum+$high-$low}]
                incr spread_count
            }
            if {[dict exists $r run]} { incr cycles_total }
            set run [field $r run]
            set x $c
            if {$axis eq "run"} { set x $run }
            foreach {value dest} [list $seed seed_points $low min_points $avg mean_points $high max_points [field $r probability] prob_points [field $r progress] progress_points] {
                if {$x ne "NaN" && $value ne "NaN"} { lappend $dest [list $x $value] }
            }
            foreach pair $offer_rows {
                lassign $pair rank val
                if {$x ne "NaN"} { dict lappend replica_sets $rank [list $x $val] }
            }
        }
        set last [lindex $cycles end]
        set tail [dict get $data $id $last]
        #output progress and performance
        puts ""
        puts "-= SWARM CV $id =-"
        puts "Info) Read $cycles_total cycles! ($num_replicas replicas; $offers_total offers)"
        puts "Info) Cycle range\t[lindex $cycles 0] - $last ($gaps missing cycle numbers)"
        puts "Info) Latest RUN\t[field $tail run]"
        puts "Info) Seed events\t$seeds_total in merged logs; [field $tail improvements] cumulative in latest log"
        puts "Info) Seed production\t[show [ratio $closed_seeds $eligible]] % ($closed_seeds / $eligible cycles)"
        puts "Info) SWARM probability\t[show [field $tail probability]] (latest logged ratio)"
        puts "Info) Seed progress\t[show [field $tail progress]] (latest logged ratio)"
        puts "Info) First/current seed\t[show $first_seed] / [show $seed]"
        if {$first_seed ne "NaN"} {
            puts "Info) Net seed change\t[show [expr {$seed-$first_seed}]] (signed, current minus first logged seed)"
        }
        puts "Info) Last seed\tcycle $last_seed, replica $seed_rank"
        if {$last_seed ne "NaN"} {
            puts "Info) Current stagnation\t[expr {$last-$last_seed}] CV cycles"
        }
        if {$last_seed_run ne "NaN" && [field $tail run] ne "NaN" && [field $tail run] >= $last_seed_run} {
            puts "Info) Current stagnation\t[expr {[field $tail run]-$last_seed_run}] RUNs (through latest SWARM cycle)"
        }
        puts "Info) Longest stagnation\t$longest_idle CV cycles (within supplied history)"
        if {$last_seed_run ne "NaN"} {
            puts "Info) Longest stagnation\t$longest_run_idle RUNs (after a known seed)"
        }

        if {[llength $intervals]} {
            set interval_sum 0.0
            foreach interval $intervals { set interval_sum [expr {$interval_sum+$interval}] }
            puts "Info) Mean seed interval\t[show [expr {$interval_sum/[llength $intervals]}]] CV cycles ([llength $intervals] intervals)"
        }
        if {$spread_count} {
            puts "Info) Mean offer spread\t[show [expr {$spread_sum/$spread_count}]] (max - min, $spread_count cycles)"
        }

        #dynamic SWARM scheduling is distinct from seed stagnation
        puts ""
        puts "-= SWARM CYCLE SPACING (RUNs, same CV) =-"
        if {[llength $run_intervals]} {
            set sorted_intervals [lsort -integer $run_intervals]
            set interval_count [llength $sorted_intervals]
            set spacing_sum 0.0
            foreach interval $run_intervals { set spacing_sum [expr {$spacing_sum+$interval}] }
            set middle [expr {$interval_count/2}]
            set median [lindex $sorted_intervals $middle]
            if {$interval_count % 2 == 0} {
                set median [expr {0.5*($median+[lindex $sorted_intervals [expr {$middle-1}]])}]
            }
            puts [format "%10s %10s %10s %10s %10s %10s" "Intervals" "Latest" "Mean" "Median" "Min" "Max"]
            puts [format "%10d %10s %10s %10s %10d %10d" $interval_count [show $spacing_latest] [show [expr {$spacing_sum/$interval_count}]] [show $median] [lindex $sorted_intervals 0] [lindex $sorted_intervals end]]
        } else {
            puts "Info) No consecutive SWARM intervals available"
        }
        if {$spacing_skipped} { puts "Info) Omitted $spacing_skipped intervals with missing cycles or invalid RUN spacing" }
        puts ""
        puts "-= SEED PRODUCTION BY REPLICA =-"
        puts [format "%7s %10s %10s %15s %18s" "Replica" "Offers" "Seeds" "Seeds/offer %" "Share of seeds %"]
        foreach rank $replica_ids {
            set offered  0
            set produced 0
            if {[dict exists $attempts $rank]} { set offered [dict get $attempts $rank] }
            if {[dict exists $producers $rank]} { set produced [dict get $producers $rank] }
            puts [format "%7d %10d %10d %15s %18s" $rank $offered $produced [show [ratio $produced $offered]] [show [ratio $produced $closed_seeds]]]
        }
        if {$summary_only} { continue }
        #write xmgrace projects
        set base ${prefix}_${id}
        #hold the logged best score constant until the next seed update
        set best_steps {}
        set previous_value NaN
        foreach point $seed_points {
            lassign $point x value
            if {$previous_value ne "NaN" && $value != $previous_value} {
                lappend best_steps [list $x $previous_value]
            }
            lappend best_steps $point
            set previous_value $value
        }
        grace ${base}_progress.agr "SWARM CV $id progress" $axis "Best seed score (logged units)" [list "Current best seed" $best_steps]
        grace ${base}_spread.agr "SWARM CV $id offer spread" $axis "CV value (logged units)" [list "Offer minimum" $min_points "Offer mean" $mean_points "Offer maximum" $max_points]
        grace ${base}_intervals.agr "SWARM CV $id cycle spacing" $axis "RUNs between SWARM cycles" [list "SWARM spacing" $interval_points]
        grace ${base}_rates.agr "SWARM CV $id ratios" $axis "Logged ratio" [list "SWARM_PROBABILITY" $prob_points "SEED_PROGRESS" $progress_points]
        set sets {}
        foreach rank [lsort -integer [dict keys $replica_sets]] { lappend sets "Replica $rank" [dict get $replica_sets $rank] }
        grace ${base}_replicas.agr "SWARM CV $id offers" $axis "CV value (logged units)" $sets
        puts "Info) Wrote ${base}_{progress,spread,replicas,rates,intervals}.agr"
    }
}
if {[catch {main} msg]} { puts stderr "Error) $msg"; exit 1 }
